---
- name: Install Apache with Ansible
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache2
      apt: name=apache2 update_cache=yes state=latest
 
    - name: Install Apache2 Module Rewrite
      apache2_module: name=rewrite state=present
      notify:
        - RESTART APACHE2
 
  handlers:
    - name: RESTART APACHE2
      service: name=apache2 state=restarted 